-- Add comprehensive fields to contacts table
ALTER TABLE public.contacts 
ADD COLUMN contact_owner TEXT,
ADD COLUMN account_name_id UUID REFERENCES public.companies(id) ON DELETE SET NULL,
ADD COLUMN account_name TEXT,
ADD COLUMN vendor_name_id UUID,
ADD COLUMN vendor_name TEXT,
ADD COLUMN contact_name TEXT,
ADD COLUMN description TEXT,
ADD COLUMN email_opt_out BOOLEAN DEFAULT false,
ADD COLUMN salutation TEXT,
ADD COLUMN last_activity_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN tag TEXT,
ADD COLUMN reporting_to_id UUID REFERENCES public.contacts(id) ON DELETE SET NULL,
ADD COLUMN reporting_to TEXT,
ADD COLUMN unsubscribed_mode TEXT,
ADD COLUMN unsubscribed_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN change_log_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN first_visit TIMESTAMP WITH TIME ZONE,
ADD COLUMN visitor_score INTEGER,
ADD COLUMN referrer TEXT,
ADD COLUMN average_time_spent_minutes DECIMAL(8,2),
ADD COLUMN most_recent_visit TIMESTAMP WITH TIME ZONE,
ADD COLUMN first_page_visited TEXT,
ADD COLUMN number_of_chats INTEGER DEFAULT 0,
ADD COLUMN days_visited INTEGER DEFAULT 0,
ADD COLUMN general_phone TEXT,
ADD COLUMN direct_phone TEXT,
ADD COLUMN linkedin_connection TEXT,
ADD COLUMN account_egnyte_link TEXT,
ADD COLUMN name_pronunciation TEXT,
ADD COLUMN industry_fb_group_memberships TEXT,
ADD COLUMN role_in_deals TEXT,
ADD COLUMN street TEXT,
ADD COLUMN city TEXT,
ADD COLUMN zip_code TEXT,
ADD COLUMN state TEXT,
ADD COLUMN country TEXT,
ADD COLUMN county TEXT,
ADD COLUMN locked BOOLEAN DEFAULT false,
ADD COLUMN last_enriched_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN enrich_status TEXT,
ADD COLUMN reference_type TEXT,
ADD COLUMN reference_subject_matter TEXT,
ADD COLUMN reference_egnyte_link TEXT,
ADD COLUMN reference_services_products TEXT,
ADD COLUMN conferences_organizations_attended TEXT;