-- Create a view that maps database columns to CSV column names for import
CREATE OR REPLACE VIEW public.contacts_import_view AS
SELECT 
  record_id AS "Record Id",
  contact_owner_id AS "Contact Owner.id",
  contact_owner AS "Contact Owner",
  lead_source AS "Lead Source",
  first_name AS "First Name",
  last_name AS "Last Name",
  account_name_id AS "Account Name.id",
  account_name AS "Account Name",
  vendor_name_id AS "Vendor Name.id",
  vendor_name AS "Vendor Name",
  email AS "Email",
  title AS "Title",
  department AS "Department",
  phone AS "Phone",
  mobile AS "Mobile",
  created_by_id AS "Created By.id",
  created_by AS "Created By",
  modified_by_id AS "Modified By.id",
  modified_by AS "Modified By",
  created_time AS "Created Time",
  modified_time AS "Modified Time",
  contact_name AS "Contact Name",
  description AS "Description",
  email_opt_out AS "Email Opt Out",
  salutation AS "Salutation",
  last_activity_time AS "Last Activity Time",
  tag AS "Tag",
  reporting_to_id AS "Reporting To.id",
  reporting_to AS "Reporting To",
  unsubscribed_mode AS "Unsubscribed Mode",
  unsubscribed_time AS "Unsubscribed Time",
  change_log_time AS "Change Log Time",
  first_visit AS "First Visit",
  visitor_score AS "Visitor Score",
  referrer AS "Referrer",
  average_time_spent_minutes AS "Average Time Spent (Minutes)",
  most_recent_visit AS "Most Recent Visit",
  first_page_visited AS "First Page Visited",
  number_of_chats AS "Number Of Chats",
  days_visited AS "Days Visited",
  general_phone AS "General Phone",
  direct_phone AS "Direct Phone",
  linkedin_connection AS "LinkedIn Connection",
  account_egnyte_link AS "Account Egnyte Link",
  name_pronunciation AS "Name Pronunciation",
  industry_fb_group_memberships AS "Industry & FB Group Memberships",
  role_in_deals AS "Role in deals",
  street AS "Street",
  city AS "City",
  zip_code AS "Zip Code",
  state AS "State",
  country AS "Country",
  county AS "County",
  locked AS "Locked",
  last_enriched_time AS "Last Enriched Time",
  enrich_status AS "Enrich Status",
  reference_type AS "Reference Type",
  reference_subject_matter AS "Reference Subject Matter, Use Case & Department",
  reference_egnyte_link AS "Reference Egnyte Link",
  reference_services_products AS "Reference Services Products & Solutions",
  conferences_organizations_attended AS "Conferences & Organizations Attended",
  id,
  user_id,
  company_id,
  notes,
  created_at,
  updated_at
FROM public.contacts;