// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdrppzblasrdytafgpvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcnBwemJsYXNyZHl0YWZncHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTQyNDUsImV4cCI6MjA2ODk3MDI0NX0.fgWtQs8ZEQ9aADi_K_np2LTqAwumtdFnnSy0C1y_i5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});